codeql workflow for static analysis
openzfsonosx/openzfs pull request #114
Opened 2022-10-26 05:44 UTC by andrewc12

ala https://github.com/openzfs/zfs/pull/14087

### Motivation and Context

### Description

### How Has This Been Tested?

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Performance enhancement (non-breaking change which improves efficiency)
- [ ] Code cleanup (non-breaking change which makes code smaller or more readable)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Library ABI change (libzfs, libzfs\_core, libnvpair, libuutil and libzfsbootenv)
- [ ] Documentation (a change to man pages or other documentation)

### Checklist:

- [ ] My code follows the OpenZFS [code style requirements](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#coding-conventions).
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**contributing** document](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md).
- [ ] I have added [tests](https://github.com/openzfs/zfs/tree/master/tests) to cover my changes.
- [ ] I have run the ZFS Test Suite with this change applied.
- [ ] All commit messages are properly formatted and contain [`Signed-off-by`](https://github.com/openzfs/zfs/blob/master/.github/CONTRIBUTING.md#signed-off-by).

2022-10-26 21:16 UTC, ryao requested changes
This should be changed to run on PRs.

2022-10-26 22:16 UTC, andrewc12 commented
> This should be changed to run on PRs.

Yeah it should. Thanks for finding this.

I also need to change the other workflow I based it on

2022-10-26 22:32 UTC, ryao commented
> > This should be changed to run on PRs.
> 
> Yeah it should. Thanks for finding this.
> 
> I also need to change the other workflow I based it on

Look at the PR for the main repository. It shows how to make this run on PRs. :)

2022-10-27 14:21 UTC, ryao approved these changes
It looks good to me, although you probably want to ask for feedback from @gmelikov. He is the one most experienced with github workflows. My knowledge on the topic is shallow compared to his.

2022-10-27 15:15 UTC, gmelikov approved these changes
LGTM code-wise, I won't challenge you on styles (unneeded commented parts). You may want to change repos' settings to make warnings fatal https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/configuring-code-scanning#defining-the-severities-causing-pull-request-check-failure

2022-10-27 15:15 UTC, gmelikov commented on .github/workflows/codeql-macos.yaml
> +          make -j 2
You may want to set it dinamically, for Linux it's `-j$(nproc)`, google tells me it's `-j$(sysctl -n hw.ncpu)` for macos

2022-10-29 01:46 UTC, andrewc12 commented
The codeQL scan for macos has 43 alerts compared to upstream which I think was 26
![chrome_screenshot_1667007927306](https://user-images.githubusercontent.com/2262876/198759032-ab591229-103f-4ffa-aaa0-f12e4f1414f7.png)

2022-10-29 01:48 UTC, andrewc12 commented
> LGTM code-wise, I won't challenge you on styles (unneeded commented parts). You may want to change repos' settings to make warnings fatal.

While this is a good idea, I don't know if existing alerts cause PR failures

2022-11-08 11:45 UTC, merged