[wip] Taskq threadpri on mac os pure
openzfsonosx/openzfs pull request #32
Opened 2021-04-14 13:55 UTC by rottegift

Make our threads less like angry bees, and give them names.

WIP: what to do about two exports :

```
kxld[net.lundman.zfs]: The following symbols are unresolved for this kext:
kxld[net.lundman.zfs]:     _thread_set_cpulimit
kxld[net.lundman.zfs]:     _throttle_set_thread_io_policy
```

These could be nerfed with just a performance impact, to keep things pure.

2021-04-14 14:05 UTC, rottegift commented
thread_set_cpulimit() is used to emulate Illumos's duty cycle, and asks xnu to limit a thread's scheduling to less than 100% of a cpu : if over a period of time the thread uses more than that, it is put to sleep for a period before being allowed to continue.

The sysdc thread is put into this mode in spa.c.    This thread is bursty, and trips the cpu limit from time to time.

throttle_set_io_policy() lets us passivate our threads so that if they generate IOKit calls they do not get counted by the IO throttle.   By default, kernel threads have high priority, so this thread serves to improve the performance of other I/O versus hdiutil-attached images in datasets (which otherwise are promoted from passive to high priority), and zvols with HFS or APFS inside.

2021-04-15 02:00 UTC, lundman requested changes

2021-04-15 02:40 UTC, rottegift commented on module/os/macos/spl/spl-thread.c
> +	thread_set_thread_name(thread, name);
lundman config/Mach.exports:_thread_set_thread_name
[03:39:40] lundman no that should just work

2021-04-15 02:40 UTC, rottegift commented on module/os/macos/spl/spl-thread.c
> +	throttle_set_thread_io_policy(priority);
OK

2021-04-15 02:43 UTC, rottegift commented on module/os/macos/spl/spl-taskq.c
> +		int ret = thread_set_cpulimit(THREAD_CPULIMIT_BLOCK,
OK, and also the prototype

2021-04-15 03:47 UTC, merged